# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
