# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20171021_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
